### ISSUE TITLE
map "m" is missing zoom and position

### ISSUE THREAD

**Issue by fly-77** [Outerra/anteworld#14]
missing zoom for the in-game map which is brough up with the "m" key. Also position arrow missing

**Comment by cameni** [comment]
It doesn't have zoom because you don't have a mouse cursor to click it with. As soon as you have some UI or if you press forced-interactive mode (tilde key) it appears.
Also I have the position arrow there ...

![image](https://github.com/user-attachments/assets/94daf255-9871-4ebc-9571-3edfa92f5975)
